export const PERMISSIONS = {
  ALL: "ALL",
  CUSTOMER_MANAGE: "CUSTOMER_MANAGE",
  PET_MANAGE: "PET_MANAGE",
  APPOINTMENT_MANAGE: "APPOINTMENT_MANAGE",
  HOTEL_MANAGE: "HOTEL_MANAGE",
  SERVICE_MANAGE: "SERVICE_MANAGE",
  INVOICE_MANAGE: "INVOICE_MANAGE",
  APPOINTMENT_VIEW: "APPOINTMENT_VIEW",
  MEDICAL_RECORD_MANAGE: "MEDICAL_RECORD_MANAGE",
  PET_VIEW: "PET_VIEW",
  INVOICE_VIEW: "INVOICE_VIEW",
} as const;
