export const ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  DOKTER: "DOKTER",
  CUSTOMER: "CUSTOMER",
} as const;

export const ROLE_OPTIONS = Object.values(ROLES);

export const ROLE_PERMISSIONS = {
  OWNER: ["ALL"],
  ADMIN: ["CUSTOMER_MANAGE", "PET_MANAGE", "APPOINTMENT_MANAGE", "HOTEL_MANAGE", "SERVICE_MANAGE", "INVOICE_MANAGE"],
  DOKTER: ["APPOINTMENT_VIEW", "MEDICAL_RECORD_MANAGE"],
  CUSTOMER: ["PET_VIEW", "APPOINTMENT_VIEW", "INVOICE_VIEW"],
} as const;
